### ISSUE TITLE
bevy main branch

### ISSUE THREAD

**Issue by slyedoc** [BlackPhlox/bevy_dolly#4]
Just found this repo, looking forward to using it.

Thoughts on a bevy main branch?  Created a [fork](https://github.com/slyedoc/bevy_dolly) that works with main currently.

Notes: 
- Had to add a wrapper to CameraRig for Component unless I am missing something.
- Updated QuerySets, some were not filtered and returning the `With<?>`, I realize it has no effect really, was it there for reason?

The query state changes lead to code like this, is there a cleaner way to handle [E0716](https://doc.rust-lang.org/error-index.html#E0716)
```rust
    let mut q2 = query.q2();
    let mut rig = q2.single_mut();
    rig.0.driver_mut.....
```

**Comment by BlackPhlox** [comment]
Looking good! I haven't been looking at migrating to main before I was sure that the 0.6 was coming. But this is a great contribution! 🎉 I've created a `0.6` branch, that you're very welcome to make a pull request to that branch.

About the notes:
- Yes, Component derive is required now, so that is correct
- I'm not sure if I understand correctly, I'm using the `With` filter so when people use the example and create another camera, the newly added camera will not be affected by `bevy_dolly`

In terms of query state, I haven't been looking into it, so I wound't know. Though E0716 can always be handled by rearranging calls and create an immutable variable, you can look at [this example](https://github.com/BlackPhlox/bevy_dolly/blob/agn_systems/examples/custom/turret_follow.rs#L130-L149) in the `agn_systems` branch.

**Comment by BlackPhlox** [comment]
Going to do a total refactor using 0.7's newtype and will match better with main, giving dolly a better upstream potential
